### ISSUE TITLE
Timer:after() does not work with recursion

### ISSUE THREAD

**Issue by ninguem26** [SSYGEN/chrono#2]
When executing the code below the function sends an error message shortly after the first iteration. Apparently this occurs because the function received by the action parameter becomes nil.

`	timer:after(1, function(f)
		print(math.random())
        timer:after(1, f)
    end)`

Error message:
>Error: libs/Timer.lua:42: attempt to call field 'action' (a nil value)
>stack traceback:
>        libs/Timer.lua:42: in function 'update'
>        main.lua:23: in function 'update'
>        [string "boot.lua"]:464: in function <[string "boot.lua"]:436>
>        [C]: in function 'xpcall'

**Comment by nyorem** [comment]
I had the same issue: the fix is easy (see https://github.com/nyorem/chrono/commit/8176cd24f96c1fdbab636e7139f0853498d89462). I don't know if this is the correct way to do it but it works for me.

**Comment by ninguem26** [comment]
I tried it here and it worked! Thank you!
