### ISSUE TITLE
Possible incompatibility with Löve 11.0

### ISSUE THREAD

**Issue by coelhucas** [SSYGEN/chrono#4]
I was following your tutorial at https://github.com/SSYGEN/blog/issues/16 and realized that when I do this:
```
	for i = 10, 0, -1 do
		timer:after(0.5, print(love.math.random()))
	end
```

After the prints, I get this error:
`Error

libraries/timer.lua:42: attempt to call field 'action' (a nil value)

Traceback

libraries/timer.lua:42: in function 'update'
main.lua:69: in function 'update'
main.lua:35: in function <main.lua:17>
[C]: in function 'xpcall'`

**Comment by flamendless** [comment]
You need to pass an anonymous function.

```
for i = 10, 0, -1 do
  timer:after(0.5, function()
    print(love.math.random())
  end))
end
```

**Comment by coelhucas** [comment]
Oh, my bad. Thank you!
